# Generated by Django 5.2.3 on 2025-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='year',
            field=models.CharField(default='2025', max_length=10),
        ),
    ]
